### ISSUE TITLE
ContextModule issue

### ISSUE THREAD

**Issue by Tijs-2** [dinject/dinject#37] opened 2020-02-28 10:46 UTC
Hello Rob,

First of all, I really like this project and the simplicity of using a library vs an entire framework like quarkus.io.

But I also have a question/issue (not sure if this is the right place but could not find a better one :) ).
I have created a CoffeeApp like application with modules. Now I can run it inside IntelliJ and one module will load the other module with the ContextModule and resolve the dependencies.

But I also tried making a Jar file and then it failed, I get the following error:
`Module [<applicationmodule>] has unsatisfied dependencies on modules: [<library module>]. Modules that were loaded ok are:[]. Consider using BootContext.withIgnoreMissingModuleDependencies() or BootContext.withSuppliedBeans(...)`

After some searching I found that the issue is that this file is overwritten in the META-INF/services folder:
io.dinject.core.BeanContextFactory
When I add both _di$Factory lines manually to the <applicationmodule>'s version it will load.

So my question is: Is it possible to create a complete file with the modules in the correct order when building the project? Or am I creating the jar file incorrectly?

Best regards,
Tijs

**Comment by rbygrave** [comment] 2020-02-28 21:34
> But I also have a question/issue (not sure if this is the right place b

This is the correct place.  We don't have a discussion forum etc so yes asking questions here is the right thing to do.

>  issue is that this file is overwritten in the META-INF/services folder:

Hmmm ok, that does not sound correct.

> Is it possible to create a complete file with the modules in the correct order when building the project? Or am I creating the jar file incorrectly?

I think we are talking about creating a runnable jar ... and then it not working when it's run.

Are you able to put this project on github somewhere or fork one of the examples so then I could reproduce the problem.

Thanks, Rob.

**Comment by Tijs-2** [comment] 2020-03-02 10:25
Hallo Rob,

Sorry for the late reply, I was not home this weekend.
But I cloned the Coffee app and changed as little as possible: https://github.com/Tijs-2/CoffeeApp

First I build it with "mvn package"
Then copy the jar file like this: "copy coffee.app.main\target\Service.jar ." (I am in the root of the project)
Finally I run the application like this: "java -jar Service.jar" then I get the following error:
`Caused by: java.lang.IllegalStateException: Module [coffee-main] has unsatisfied dependencies on modules: [coffee-pump] [coffee-heater]. Modules that were loaded ok are:[]. Consider using BootContext.withIgnoreMissingModuleDependencies() or BootContext.withSuppliedBeans(...)`

To fix it I changed the "target/classes/META-INF/services/io.dinject.core.BeanContextFactory" file
to this before running the "mvn package" command:
`
coffee.app.heater._di$Factory
coffee.app.pump._di$Factory
coffee.app.main._di$Factory
`

Tijs

**Comment by rbygrave** [comment] 2020-03-04 23:02
Sorry, been busy with stuff ... I'll get to this over the next few days. 

Cheers, Rob.

**Comment by Tijs-2** [comment] 2020-03-11 08:59
Hi Rob,

I was wondering if you had the time to look at this?
And/Or can I do something to improve my example?

Thanks,
Tijs

**Comment by rbygrave** [comment] 2020-03-11 12:13
I haven't got to this yet. I've got busy this last week or so  preparing the next release for Ebean ORM -  https://github.com/ebean-orm/ebean 

I should get to look at this on the weekend or maybe before.

**Comment by Tijs-2** [comment] 2020-03-11 12:32
No problem was just wondering if I could do something to help

But I also like your ebean library, must admit as far as I know, the best database library out there. Also the reason why I found this one :)

**Comment by Tijs-2** [comment] 2020-03-27 14:32
Hi Rob,

I found a solution for the problem, and it is a very simple one.
I have added the following lines to the "maven-shade-plugin" plugin:
`
<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
  <resource>META-INF/services/io.dinject.core.BeanContextFactory</resource>
</transformer>
'

It then combines the files instead of overwriting the files

I do have another question: Is this software usable for production software and are you maintaining it. Or is it a sample project to test of this functionality works? Because I think it is quite good now I am trying it out some more.

Tijs

**Comment by rbygrave** [comment] 2020-03-29 19:47
*> maven-shade-plugin*

Ok cool. I rarely use the shade plugin these days.


*> Is this software usable for production software *

Yes. I'd say so, I personally have a lot of faith in it because it is
literally so simple and small - there really isn't much to it.


*>  are you maintaining it. *

I do my best. That said it is nice and simple with no more features to add
so to date there it hasn't needed much time.


Cheers, Rob.

**Comment by rbygrave** [comment] 2020-04-12 04:54
I think we can close this issue.

**Closed by rbygrave** 2020-04-12 04:54 UTC

**Comment by Tijs-2** [comment] 2020-04-12 12:53
Yes, sorry was completely behind some other work that I forgot to close this issue.
But thank you for your support!

Tijs
